// Generated by CoffeeScript 2.0.0-beta5
void function () {
  var app, buildPath, cachePath, cjse, escodegen, escodegenFormat, esmangle, express, fs, mktemp, npm, path, port, rimraf, url;
  fs = require('fs');
  path = require('path');
  url = require('url');
  cjse = require('commonjs-everywhere');
  escodegen = require('escodegen');
  esmangle = require('esmangle');
  express = require('express');
  mktemp = require('mktemp');
  npm = require('npm');
  rimraf = require('rimraf');
  escodegenFormat = {
    indent: {
      style: '',
      base: 0
    },
    renumber: true,
    hexadecimal: true,
    quotes: 'auto',
    escapeless: true,
    compact: true,
    parentheses: false,
    semicolons: false
  };
  cachePath = path.resolve('cache');
  buildPath = path.resolve('build');
  if (!fs.existsSync(cachePath))
    fs.mkdirSync(cachePath);
  if (!fs.existsSync(buildPath))
    fs.mkdirSync(buildPath);
  app = express();
  app.get(/^\/bundle\/([^@]+)(?:@(.+))?$/, function (req, res) {
    var pkg, version;
    pkg = req.params[0];
    version = req.params[1] || 'latest';
    console.dir(req.params);
    return npm.load({}, function () {
      return npm.commands.info(['' + pkg + '@' + version], function (err, infoResult) {
        var cacheFile, cacheFileName, entry, registryEntry, tempBuildDir, v;
        if (err) {
          res.send(404, err.toString());
          res.end();
          return;
        }
        for (v in infoResult) {
          if (!isOwn$(infoResult, v))
            continue;
          entry = infoResult[v];
          registryEntry = entry;
        }
        if (version === 'latest')
          version = registryEntry.version;
        cacheFileName = '' + pkg + '@' + version + '-' + registryEntry.dist.shasum + '.js';
        cacheFile = path.join(cachePath, cacheFileName);
        if (fs.existsSync(cacheFile)) {
          res.type('javascript');
          res.attachment(cacheFileName);
          res.send(200, fs.readFileSync(cacheFile));
          return;
        }
        tempBuildDir = mktemp.createDirSync(path.join(buildPath, '' + pkg + '@' + version + '-XXXXXX'));
        fs.writeFileSync(path.join(tempBuildDir, 'package.json'), '{"name": "name"}');
        npm.prefix = tempBuildDir;
        return npm.commands.install([registryEntry.dist.tarball], function (err, installOutput) {
          var bundle, entryFile, js, outputFile, pkgSlug, root;
          try {
            if (err)
              throw err;
            root = path.normalize(path.join(tempBuildDir, 'node_modules', pkg));
            entryFile = path.join(root, registryEntry.main || 'index.js');
            outputFile = path.normalize(path.join(tempBuildDir, 'bundle.js'));
            pkgSlug = pkg.replace(/^[^$_a-z]/i, '_').replace(/[^a-z0-9$_]/gi, '_');
            bundle = cjse.cjsify(entryFile, root, {
              'export': pkgSlug,
              ignoreMissing: true
            });
            bundle = esmangle.mangle(esmangle.optimize(bundle), { destructive: true });
            js = escodegen.generate(bundle, { format: escodegenFormat });
            fs.writeFileSync(outputFile, js);
            fs.renameSync(outputFile, cacheFile);
            rimraf.sync(tempBuildDir);
            res.type('javascript');
            res.attachment(cacheFileName);
            return res.send(200, js);
          } catch (e$) {
            err = e$;
            res.send(500, err.toString());
            return res.end();
          } finally {
            return rimraf.sync(tempBuildDir);
          }
        });
      });
    });
  });
  port = process.env.PORT || 3e3;
  app.listen(port);
  console.log('Listening on port ' + port);
  function isOwn$(o, p) {
    return {}.hasOwnProperty.call(o, p);
  }
}.call(this);
